[package]
name = "net"
version.workspace = true
edition.workspace = true

[dependencies]
proto.workspace = true
tokio.workspace = true
tokio-util.workspace = true
bytes.workspace = true
prost.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
figment.workspace = true
thiserror.workspace = true
sysinfo.workspace = true
futures.workspace = true
