[package]
name = "dummy_client"
version.workspace = true
edition.workspace = true

[dependencies]
proto.workspace = true
net.workspace = true
db.workspace = true
tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde.workspace = true
crossterm.workspace = true

[dev-dependencies]
login_server = { path = "../login_server" }
game_server = { path = "../game_server" }
